Repository NixOS-Pilots/pilots, pull requests merged in 2024-03, with the labels that each got.

#1 chore: add codeowners
  CODEOWNERS
Labels: chore

#2 feat(flake): bootstrap project, add pre-commit-hooks
  flake.lock
  flake.nix
  justfile
Labels: feature

#3 feat(pkgs): add glider
  .gitignore
  flake.nix
  pkgs/glider/default.nix
Labels: feature

#4 chore: add editorconfig
  .editorconfig
Labels: chore

#5 chore: update LICENSE statement
  LICENSE
  README.md
Labels: chore

#6 chore: add pre-commit-config
  .pre-commit-config.yaml
Labels: chore

#7 patch(pre-commit-config): update hooks config
  .pre-commit-config.yaml
Labels: patch

#8 docs: update README
  README.md
Labels: documentation

#9 feat(flake): add inputs.nix-fast-build
  flake.lock
  flake.nix
  justfile
Labels: feature

#10 chore(flake): update flake description
  flake.nix
Labels: chore

#11 docs(readme): update social groups
  README.md
Labels: documentation

#12 feat(pkgs): onboard qutebrowser
  flake.nix
  justfile
  pkgs/qutebrowser/default.nix
  pkgs/qutebrowser/fix-restart.patch
Labels: feature

#13 feat(pkgs): onboard neovim; integrate flake-compat
  flake.lock
  flake.nix
  lib/default.nix
  lib/flake-compat.nix
  pkgs/glider/default.nix
  pkgs/neovim/default.nix
  pkgs/qutebrowser/default.nix
Labels: feature

#14 docs(readme): add binary cache notes
  README.md
Labels: documentation

#15 patch(pkgs/qutebrowser): sync upstream
  pkgs/qutebrowser/default.nix
  pkgs/qutebrowser/metadata.json
Labels: patch

#16 ci(justfile): add build-push recipe
  justfile
Labels: ci

#17 patch: apply minor fixes
  justfile
  pkgs/neovim/default.nix
Labels: patch

#18 chore(pkgs): update qutebrowser -> 3d86d78
  pkgs/qutebrowser/metadata.json
Labels: chore
